version: '3.5'
services:
    spotiapp-web:
        container_name: spotiapp-web
        build: ./docker/apache72nodejs
        ports:
            - "3000:3000"
            - "4200:4200"
        volumes:
            - ./:/var/www/html
        tty: true        # docker run -t
        stdin_open: true # docker run -i
