version: '3.5'
services:
    spa-db:
        container_name: spa-db
        build:
            context: ./docker/database
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: 'spa_db'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./backup/var/lib/mysql:/var/lib/mysql
            - ./backup/etc/mysql/mysql.conf.d/:/etc/mysql/mysql.conf.d/
    spa-web:
        container_name: spa-web
        build: ./docker/apache72nodejs
        environment:
            - TERM=${TERM}
            - XDEBUG_CONFIG=remote_host=host.docker.internal
            - PHP_IDE_CONFIG=serverName=localhost # for console debugging
        depends_on:
            - spa-db
        ports:
            - "83:80"
            - "446:443"
            - "3000:3000"
            - "4200:4200"
            - "9003:9003"
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/html
        links:
            - spa-db:mysql
    spa-phpmyadmin:
        container_name: spa-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: spa-db
        depends_on:
            - spa-db
    

    
