version: '3.5'

services:
  node:
    container_name: node
    build:  
      context: ./docker/node
    ports: 
      - "8888:8081"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "npm start"

