# specify the node base image with your desired version node:<version>
FROM node:16

ENV http_proxy "http://10.7.6.219:3128"
ENV https_proxy "http://10.7.6.219:3128"

# replace this with your application's default port
EXPOSE 3000
